name: Build and Deploy to Azure Container Instances

on:
  push:
    branches: [ main ]

env:
  REGISTRY_NAME: myappregistry2001
  RESOURCE_GROUP: my-container-app-rg
  CONTAINER_NAME: my-web-app-container

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t $REGISTRY_NAME.azurecr.io/my-web-app:${{ github.sha }} .

    - name: Login to Azure Container Registry
      run: |
        az acr login --name $REGISTRY_NAME

    - name: Push Docker image to ACR
      run: |
        docker push $REGISTRY_NAME.azurecr.io/my-web-app:${{ github.sha }}

    - name: Stop existing container
      run: |
        # Delete existing container without --no-wait
        az container delete --name $CONTAINER_NAME --resource-group $RESOURCE_GROUP --yes || echo "No existing container to delete"

    - name: Deploy new container instance
      run: |
        # Create new container instance with Linux OS type
        az container create \
          --resource-group $RESOURCE_GROUP \
          --name $CONTAINER_NAME \
          --image $REGISTRY_NAME.azurecr.io/my-web-app:${{ github.sha }} \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --dns-name-label mywebapp-$(echo ${{ github.sha }} | cut -c1-8) \
          --ports 80 \
          --os-type Linux \
          --cpu 1 \
          --memory 1 \
          --restart-policy Always

    - name: Get Application URL
      run: |
        echo "🎉 Application successfully deployed!"
        echo "🌐 Your application is available at:"
        az container show --resource-group $RESOURCE_GROUP --name $CONTAINER_NAME --query ipAddress.fqdn -o tsv
        echo ""
        echo "📊 Container status:"
        az container show --resource-group $RESOURCE_GROUP --name $CONTAINER_NAME --query instanceView.state -o tsv
